services:
  stats-server:
    build:
      context: ./ewm-stats/stats-server
    image: ewm-stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d stats" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ewm-service:
    build:
      context: ./ewm-main
    image: ewm-main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - STATS_CLIENT_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres  -d main"]
      interval: 5s
      timeout: 5s
      retries: 10