server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stats
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
